"""add_hospital_id_to_productions

Revision ID: 0195364a57ee
Revises: c5ea2e744bc0
Create Date: 2026-01-30 21:26:26.894636

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0195364a57ee'
down_revision: Union[str, None] = 'c5ea2e744bc0'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
