"""rename_valor_to_amount

Revision ID: 02f2d5d04257
Revises: 8de639df6f84
Create Date: 2026-02-01 20:16:32.046157

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '02f2d5d04257'
down_revision: Union[str, None] = '8de639df6f84'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('repasses', 'valor', new_column_name='amount')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('repasses', 'amount', new_column_name='valor')
    # ### end Alembic commands ###
