"""create repasses table

Revision ID: 3940d94fd0b7
Revises: fcd9374b8a55
Create Date: 2026-01-30 21:52:04.970688

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3940d94fd0b7'
down_revision: Union[str, None] = 'fcd9374b8a55'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('repasses',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('production_id', sa.UUID(), nullable=False),
    sa.Column('valor', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['production_id'], ['productions.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_repasses_production_id'), 'repasses', ['production_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_repasses_production_id'), table_name='repasses')
    op.drop_table('repasses')
    # ### end Alembic commands ###
