"""create_hospitals_and_doctor_hospital_tables

Revision ID: 5511ebfa4c49
Revises: 940524c7f969
Create Date: 2026-01-30 20:32:08.680972

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5511ebfa4c49'
down_revision: Union[str, None] = '940524c7f969'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
