"""add status to repasse

Revision ID: 9090ef2c5ddc
Revises: 3940d94fd0b7
Create Date: 2026-01-31 02:58:30.559807

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9090ef2c5ddc'
down_revision: Union[str, None] = '3940d94fd0b7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('repasses', sa.Column('status', sa.Enum('PENDENTE', 'CONSOLIDADO', name='repassestatus'), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('repasses', 'status')
    # ### end Alembic commands ###
