"""add_user_id_to_models

Revision ID: fd5ebbbba863
Revises: fdb9687fbf8c
Create Date: 2026-02-01 21:14:33.957661

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'fd5ebbbba863'
down_revision: Union[str, None] = 'fdb9687fbf8c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('doctors', sa.Column('user_id', sa.UUID(), nullable=False))
    op.create_foreign_key(None, 'doctors', 'users', ['user_id'], ['id'])
    op.add_column('hospitals', sa.Column('user_id', sa.UUID(), nullable=False))
    op.create_foreign_key(None, 'hospitals', 'users', ['user_id'], ['id'])
    op.add_column('productions', sa.Column('user_id', sa.UUID(), nullable=False))
    op.create_foreign_key(None, 'productions', 'users', ['user_id'], ['id'])
    op.add_column('repasses', sa.Column('user_id', sa.UUID(), nullable=False))
    op.create_foreign_key(None, 'repasses', 'users', ['user_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'repasses', type_='foreignkey')
    op.drop_column('repasses', 'user_id')
    op.drop_constraint(None, 'productions', type_='foreignkey')
    op.drop_column('productions', 'user_id')
    op.drop_constraint(None, 'hospitals', type_='foreignkey')
    op.drop_column('hospitals', 'user_id')
    op.drop_constraint(None, 'doctors', type_='foreignkey')
    op.drop_column('doctors', 'user_id')
    # ### end Alembic commands ###
